### ISSUE TITLE
Отправка результатов от лица юзера

### ISSUE THREAD

**Issue by vehsamrak** [Vehsamrak/slack-standup#14]

**Comment by tblack192** [comment]
вроде уже так работает)

**Comment by vehsamrak** [comment]
Сейчас отправляет от своего лица, и делает mention того, от чьего лица действует.
![Screenshot from 2020-11-19 16-17-28](https://user-images.githubusercontent.com/4052919/99671232-ce49f300-2a82-11eb-8728-c13aa9fa87c9.png)
